module load apps/gcc/R/4.4.2
Rscript p1_temporalv_combine_cohorts.R > p1_temporalv_combine_cohorts.out
Rscript p2_temporalv_layer_cohort_split_times.R 1 > p2_temporalv_layer_cohort_split_times1.out
Rscript p2_temporalv_layer_cohort_split_times.R 2 > p2_temporalv_layer_cohort_split_times2.out
Rscript p2_temporalv_layer_cohort_split_times.R 3 > p2_temporalv_layer_cohort_split_times3.out
Rscript p2_temporalv_layer_cohort_split_times.R 4 > p2_temporalv_layer_cohort_split_times4.out
Rscript p2_temporalv_layer_cohort_split_times.R 5 > p2_temporalv_layer_cohort_split_times5.out
Rscript p3_temporalv_test_cohort_sizes_match.R > p3_temporalv_test_cohort_sizes_match.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 1 1 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_1_1.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 1 2 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_1_2.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 1 3 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_1_3.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 1 4 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_1_4.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 1 5 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_1_5.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 2 1 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_2_1.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 2 2 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_2_2.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 2 3 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_2_3.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 2 4 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_2_4.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots.R 2 5 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_2_5.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 1 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_1.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 2 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_2.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 3 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_3.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 4 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_4.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 5 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_5.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 1 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_1.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 2 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_2.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 3 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_3.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 4 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_4.out
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 5 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_5.out
Rscript p5_temporalv_initial_layer_prototype3_d1v1.R > p5_temporalv_initial_layer_prototype3_d1v1.out
Rscript p6_temporalv_intervention_layer_prototype3_d1v1.R > p6_temporalv_intervention_layer_prototype3_d1v1.out
