module load apps/gcc/R/4.4.2
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 1 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_1.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 2 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_2.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 3 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_3.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 4 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_4.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 1 5 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_1_5.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 1 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_1.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 2 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_2.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 3 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_3.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 4 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_4.out &
Rscript p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime.R 2 5 > p4_temporalv_prototype3_calculcate_cf_surv_times_4knots_caltime_2_5.out &