---
title: "Risk scores from the worked example"
author: "Alex Pate"
date: "2025-05-14"
output: 
  html_document:
    number_sections: TRUE
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/mnt/bmh01-rds/Sperrin_CHARIOT_CPRD/alex/projectM1/")
library(knitr)
```

```{r}
###
### Code for worked example
###

### Clear workspace
rm(list=ls())
Sys.time()

### Define gender
gender <- 2

### Load survival package
library(survival)

### Source functions
R.func.sources = list.files("R", full.names = TRUE)
sapply(R.func.sources, source)

### Define HR for offsets
### lnHR_statins and lnHR_ah used when making predictions 'on treatment' in the treatment offset and unexposed mediator models
### lnHR_sbp, lnHR_bmi and lnHR_nonhdl used when making predictions in the modifiable risk factor model
lnHR_statins <- readRDS("data/offsets_total_lnHR_statins.rds")
lnHR_ah <- readRDS("data/offsets_total_lnHR_ah.rds")
lnHR_sbp <- readRDS("data/offsets_direct_lnHR_sbp.rds")
lnHR_bmi <- readRDS("data/offsets_direct_lnHR_bmi.rds")
lnHR_nonhdl <- readRDS("data/offsets_direct_lnHR_nonhdl.rds")

### Read in model and baseline hazards
fit_list <- lapply(1:4, function(x) {readRDS(paste("data/fit_", gender, "_model", x, ".rds", sep = ""))})
bhaz_list <- lapply(1:4, function(x) {readRDS(paste("data/bhaz_", gender, "_model", x, ".rds", sep = ""))})

### Add the non-causal model to the end of the list, to avoid confusion, wanted the model numbers 1 to 4 to correspond to the list element
fit_list[[length(fit_list) + 1]] <- readRDS(paste("data/fit_", gender, "_model", 0, ".rds", sep = ""))
bhaz_list[[length(bhaz_list) + 1]] <- readRDS(paste("data/bhaz_", gender, "_model", 0, ".rds", sep = ""))
```

# Non-causal model and treatment offset model

```{r}
####################################################################################################
### Start by comparing risks for non-causal model (model 0) and treatment offset model (model 1) ###
####################################################################################################

### Create a data.frame with the inputs for the indiviudal we are intereseted in
df_valid <- readRDS(paste("data/df_imp_valid_", gender, sep = ""))[1,]
colnames(df_valid)

### Set predictors to be predictors of interest
df_valid <- dplyr::mutate(df_valid, 
                          age = 65,
                          sbp = 140, 
                          bmi = 30, 
                          nonhdl = 5, 
                          IMD = 10,
                          diabetes = factor("Type2", levels = levels(diabetes)),
                          ethnicity = factor("white", levels = levels(ethnicity)))

###
### Get predicted risks
###

### Visit 1, Non-causal model, off antihypertensives
pred_model0_off_ah_visit0 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define antihypertensives
    antihypertensives = "Absent") |>
  ### Estimate survival probability
  est_surv(fit = fit_list[[5]],
           bhaz = bhaz_list[[5]],
           time = 10*365.25)

### Visit 1, Non-causal model, on antihypertensives
pred_model0_on_ah_visit0 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define antihypertensives
    antihypertensives = "Present") |>
  ### Estimate survival probability
  est_surv(fit = fit_list[[5]],
           bhaz = bhaz_list[[5]],
           time = 10*365.25)

### Visit 1, model 1, off antihyertensives
pred_model1_off_ah_visit0 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment off antihypertensives
    offset_ah_timevar_lnHR = 0) |>
  ### Estimate survival probability
  est_surv_offset(fit = fit_list[[1]],
                  bhaz = bhaz_list[[1]],
                  time = 10*365.25)

### Visit 1, model 1, on antihyertensives
pred_model1_on_ah_visit0 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment on antihypertensives
    offset_ah_timevar_lnHR = lnHR_ah) |>
  ### Estimate survival probability
  est_surv_offset(fit = fit_list[[1]],
                  bhaz = bhaz_list[[1]],
                  time = 10*365.25)

### Present risks
round(100*c(pred_model0_off_ah_visit0, pred_model0_on_ah_visit0, pred_model1_off_ah_visit0, pred_model1_on_ah_visit0), 2)


######################################################################################
### Individual initiates hypertensive therapy and achieves reduction of SBP to 120 ### 
######################################################################################

### Visit 2, off antihyertensives
pred_model1_off_ah_visit1 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment off antihypertensives
    offset_ah_timevar_lnHR = 0, 
    ### Define sbp
    sbp = 120) |>
  ### Estimate survival probability
  est_surv_offset(fit = fit_list[[1]],
                  bhaz = bhaz_list[[1]],
                  time = 10*365.25)

### Visit 2, on antihyertensives
pred_model1_on_ah_visit1 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment off antihypertensives
    offset_ah_timevar_lnHR = lnHR_ah, 
    ### Define sbp
    sbp = 120) |>
  ### Estimate survival probability
  est_surv_offset(fit = fit_list[[1]],
                  bhaz = bhaz_list[[1]],
                  time = 10*365.25)

### Compare risks to previous
round(100*c(pred_model1_off_ah_visit0, pred_model1_on_ah_visit0, pred_model1_off_ah_visit1, pred_model1_on_ah_visit1), 2)
```

# Unexposed mediator model

```{r}
########################################################
### Now move onto unexposed mediator model (model 2) ###
########################################################

### Visit 1, off antihypertensives
pred_model2_off_ah_visit0 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment off antihypertensives
    offset_ah_timevar_lnHR = 0, 
    ### Define sbp
    sbp_unexposed = 140) |>
  ### Estimate survival probability
  est_surv_offset(fit = fit_list[[2]],
                  bhaz = bhaz_list[[2]],
                  time = 10*365.25)

### Visit 1, on antihypertensives
pred_model2_on_ah_visit0 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment on antihypertensives
    offset_ah_timevar_lnHR = lnHR_ah, 
    ### Define sbp
    sbp_unexposed = 140) |>
  ### Estimate survival probability
  est_surv_offset(fit = fit_list[[2]],
                  bhaz = bhaz_list[[2]],
                  time = 10*365.25)

### There is a small increase in risk compared to model 1
round(100*c(pred_model1_off_ah_visit0, pred_model1_on_ah_visit0, pred_model2_off_ah_visit0, pred_model2_on_ah_visit0), 2)

### At visit 2, the unexposed SBP is the same, so no need to estimate any more risks
```

# Modifiable risk factor model

```{r}
###################################################################
### Now we move onto the modifiable risk factor model (model 3) ###
###################################################################

###
### Reductions of SBP from 140 to 130 and 120
###

### Get predicted risk for SBP = 140
pred_model3_sbp140 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj)  |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[3]],
    bhaz = bhaz_list[[3]],
    time = 10*365.25)

### Get predicted risk for SBP = 130
pred_model3_sbp130 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp = 130,
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj)  |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[3]],
    bhaz = bhaz_list[[3]],
    time = 10*365.25)

### Get predicted risk for SBP = 120
pred_model3_sbp120 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp = 120,
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj) |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[3]],
    bhaz = bhaz_list[[3]],
    time = 10*365.25)

### Compare risks
round(100*c(pred_model3_sbp140, pred_model3_sbp130, pred_model3_sbp120), 2)

###
### Lose 5kg intervention 
###

### Calculate the expected reduction in BMI
### We assume average UK height for women, and calculate the weight corresponding to BMI of 30
weight <- 30*1.6^2

### A reduction of 5 will result in a BMI of
bmi_new <- (weight-5)/1.6^2
wl_bmi_reduction = 30 - bmi_new
wl_bmi_reduction

### BMI -> non-HDL is 0.1043451 decrease
wl_nonhdl_reduction <- wl_bmi_reduction*0.1043451
wl_nonhdl_reduction

### BMI -> SBP is 0.7 decrease
wl_sbp_reduction <- wl_bmi_reduction*0.7
wl_sbp_reduction

###
### Get predicted risk for SBP = 140
pred_model3_bmi25 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp = sbp - wl_sbp_reduction,
    bmi = bmi - wl_bmi_reduction,
    nonhdl = nonhdl - wl_nonhdl_reduction,
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj)  |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[3]],
    bhaz = bhaz_list[[3]],
    time = 10*365.25)

### Compare risks
round(100*pred_model3_bmi25, 2)

###
### Statin intervention
###

### First calculate expected change in each MFR when using statins
### See supplementary data file 3 for these changes.

## sbp
statins_change_sbp <- -2.62
## bmi 
statins_change_bmi <- 0.33
## non-HDL cholesterol
statins_change_nonhdl <- 1.24*(-1.07)

### Calculate predicted risk under intervention at visit 0
### Get predicted risk for SBP = 140
pred_model3_statins <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp = sbp + statins_change_sbp,
    bmi = bmi + statins_change_bmi,
    nonhdl = nonhdl + statins_change_nonhdl,
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj)  |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[3]],
    bhaz = bhaz_list[[3]],
    time = 10*365.25)

### Compare risks
round(100*pred_model3_statins, 2)

###
### Reduction of all risk factors to healthy levels
###

### Get predicted risk for SBP = 140
pred_model3_healthy <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp = 120,
    bmi = 25,
    nonhdl = 2.6,
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj)  |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[3]],
    bhaz = bhaz_list[[3]],
    time = 10*365.25)

### Compare risks
round(100*pred_model3_healthy, 2)

### Create table
tbl_model3 <- data.frame(
  "intervention" = c("No intervention",
                     "SBP 130",
                     "SBP 120",
                     "weight loss",
                     "statins",
                     "healthy"),
  "risk" = round(100*c(pred_model3_sbp140,
                       pred_model3_sbp130,
                       pred_model3_sbp120,
                       pred_model3_bmi25,
                       pred_model3_statins,
                       pred_model3_healthy), 2))
knitr::kable(tbl_model3)
```

# Two-component model

```{r}
##############################################################################################
### Now we move onto the two component model (model 4)
### We will consider the same interventions as in the previous section 
##############################################################################################

### Get predicted risk for SBP = 140 from the initial risk estimation layer
pred_model4_visit0_sbp140 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj)  |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[4]],
    bhaz = bhaz_list[[4]],
    time = 10*365.25)

### Now we apply the relative risk reduction person A, using the intervention layer

### Read in other direct effects, calculated in file p1_data_prep/p8_calculate_treatment_effects.R
direct_OR_nonhdl <- readRDS("data/direct_OR_nonhdl.rds")
direct_OR_bmi <-  readRDS("data/direct_OR_bmi.rds")
direct_OR_sbp <- readRDS("data/direct_OR_sbp.rds")

### Function to apply odds ratio to a risk score, based on change in SBP, BMI and Non-HDL
convert_risk_odds <- function(p, change_sbp = 0, change_bmi = 0, change_nonhdl = 0){
  
  ### Apply the relative risk change
  or.change_sbp <- direct_OR_sbp^change_sbp
  or.change_bmi <- direct_OR_bmi^change_bmi
  or.change_nonhdl <- direct_OR_nonhdl^change_nonhdl
  
  ### Apply these RRs
  OR <-
    or.change_sbp*
    or.change_bmi*
    or.change_nonhdl
  
  ### Get odds of risk score
  odds <- p/(1-p)
  
  ### Calculate new odds
  new_odds <- odds*OR
  
  ### Convert back onto risk scale
  new_risk <- new_odds/(1+new_odds)
  
  return(new_risk)
}

###
### Reductions of SBP from 140 to 130 and 120
###

### Apply odds ratio to risk score
pred_model4_visit0_sbp130 <- convert_risk_odds(p = pred_model4_visit0_sbp140, change_sbp = -10)
pred_model4_visit0_sbp120 <- convert_risk_odds(p = pred_model4_visit0_sbp140, change_sbp = -20)

### Compare risks
round(100*c(pred_model4_visit0_sbp140, pred_model4_visit0_sbp130, pred_model4_visit0_sbp120), 2)

###
### Reduction of BMI by 5
###
pred_model4_visit0_bmi25 <- convert_risk_odds(p = pred_model4_visit0_sbp140, change_sbp = -wl_sbp_reduction, change_bmi = -wl_bmi_reduction, change_nonhdl = -wl_nonhdl_reduction)

### Compare risks
round(100*pred_model4_visit0_bmi25, 2)

###
### Statins
###
pred_model4_visit0_statins <- convert_risk_odds(p = pred_model4_visit0_sbp140, 
                                                change_sbp = statins_change_sbp, 
                                                change_bmi = statins_change_bmi, 
                                                change_nonhdl = statins_change_nonhdl)

### Compare risks
round(100*pred_model4_visit0_statins, 2)

###
### Reduction of all values to healthy level
###
pred_model4_visit0_healthy <- convert_risk_odds(p = pred_model4_visit0_sbp140, 
                                         change_sbp = -20, 
                                         change_bmi = -5, 
                                         change_nonhdl = -2.4)

### Compare risks
round(100*pred_model4_visit0_healthy, 2)

### Create table
tbl_model4 <- data.frame(
  "intervention" = c("No intervention",
                     "SBP 130",
                     "SBP 120",
                     "weight loss",
                     "statins",
                     "healthy"),
  "risk" = round(100*c(pred_model4_visit0_sbp140,
                       pred_model4_visit0_sbp130,
                       pred_model4_visit0_sbp120,
                       pred_model4_visit0_bmi25,
                       pred_model4_visit0_statins,
                       pred_model4_visit0_healthy), 2))
knitr::kable(tbl_model4)

###
### Visit 1 (first follow-up visit, three months later)
###

### Update age (only three months later, so add nothing to age)
df_valid <- dplyr::mutate(df_valid, age = age + 0)

### Get predicted risk for SBP = 140 from the initial risk estimation layer
### This is the risk if we had not intervened
pred_model4_visit1_sbp140 <- 1 - df_valid |>
  dplyr::mutate(
    ### Define treatment to be 'continue as current'
    offset_ah_timevar_lnHR = 0, 
    offset_statins_timevar_lnHR = 0,
    ### Define sbp, bmi, and non-HDL with cutoffs
    sbp_adj = dplyr::case_when(sbp < 120 ~ 0,
                               TRUE ~ sbp - 120),
    bmi_adj = dplyr::case_when(bmi < 25 ~ 0,
                               TRUE ~ bmi - 25),
    nonhdl_adj = dplyr::case_when(nonhdl < 2.6 ~ 0,
                                  TRUE ~ nonhdl - 2.6),
    ### Create offset terms for prediction
    offset_sbp_lnHR = lnHR_sbp*sbp_adj,
    offset_bmi_lnHR = lnHR_bmi*bmi_adj,
    offset_nonhdl_lnHR = lnHR_nonhdl*nonhdl_adj)  |>
  ### Estimate survival probability
  est_surv_offset(
    fit = fit_list[[4]],
    bhaz = bhaz_list[[4]],
    time = 10*365.25)

### Get the factual estimated risk based on achieved levels of MFRs
### Suppose this individual achieved a reduction of BMI of 5 and reduction in non-HDL cholesterol of 1
pred_model4_visit1_factual <- convert_risk_odds(p = pred_model4_visit1_sbp140, 
                                                change_sbp = 0, 
                                                change_bmi = -5, 
                                                change_nonhdl = -1)
round(100*pred_model4_visit1_factual, 2)

### Now estimate hypothetical risks, if that individual was to also reduce blood pressure by 10 or 20
pred_model4_visit1_hypo_sbp130 <- convert_risk_odds(p = pred_model4_visit1_sbp140, 
                                                    change_sbp = -10, 
                                                    change_bmi = -5, 
                                                    change_nonhdl = -1)

pred_model4_visit1_hypo_sbp120 <- convert_risk_odds(p = pred_model4_visit1_sbp140, 
                                                    change_sbp = -20, 
                                                    change_bmi = -5, 
                                                    change_nonhdl = -1)

round(100*pred_model4_visit1_hypo_sbp130, 2)
round(100*pred_model4_visit1_hypo_sbp120, 2)
```

# Calculations used to showcase how to implement the intervention layer

See section 3 of supplementary data file 3 (DAG derivation)

```{r}
#############################################################################
### Calculations used to showcase how to implement the intervention layer ###
### in section 3 of supplementary data file 3 (DAG derivation)
#############################################################################

###
### Arbitrary intervention acting on all MFRs
###

### First define expected change in each MFR

## sbp
arbitrary_change_sbp <- -7.5
## bmi 
arbitrary_change_bmi <- -5
## non-HDL cholesterol
arbitrary_change_nonhdl <- -1

### Apply the relative risk change
(direct_OR_sbp^arbitrary_change_sbp)*(direct_OR_bmi^arbitrary_change_bmi)*(direct_OR_nonhdl^arbitrary_change_nonhdl) # 0.5951709

### Calculate risk under intervention
pred_model4_visit0_arbitrary <- convert_risk_odds(p = pred_model4_visit0_sbp140, 
                                                change_sbp = arbitrary_change_sbp, 
                                                change_bmi = arbitrary_change_bmi, 
                                                change_nonhdl = arbitrary_change_nonhdl)
### Compare risks
round(100*pred_model4_visit0_arbitrary, 2)
```